apiVersion: v1
kind: Service
metadata:
  name: dragonfly
  labels:
    app: dragonfly
spec:
  clusterIP: None
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app: dragonfly
